const word1 = new Dictionary("cześć (na powitanie)", "привіт")
const word2 = new Dictionary("dzień dobry (od rana do południa)", "доброго ранку")
const word3 = new Dictionary("dzień dobry (po południu)", "добрий день", "доброго дня")
const word4 = new Dictionary("dobry wieczór", "добрий вечір", "доброго вечора")
const word5 = new Dictionary("cześć (na pożegnanie)", "бувай", "па-па")
const word6 = new Dictionary("do widzenia", "до побачення" ,"до застрічі")
const word7 = new Dictionary("do jutra", "до завтра")
const word8 = new Dictionary("dobranoc", "на добраніч", "добраніч")